# Generated by Django 4.1.7 on 2023-02-26 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='aluno',
            new_name='aluno_id',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='curso',
            new_name='curso_id',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='curso',
            new_name='curso_id',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos',
            field=models.ManyToManyField(to='escola.curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota1',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota2',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='serie',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
