# Generated by Django 4.1.7 on 2023-02-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_remove_aluno_serie_remove_professor_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='curso_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escola.curso'),
        ),
    ]
